micronaut:
  application:
    name: metrics
kafka:
  bootstrap:
    servers: localhost:29092
  streams:
     word-count:
        processing.guarantee: "exactly_once"
        auto.offset.reset: "earliest"

